version: '3.1'

services:

  db_flask2:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: post123
      MYSQL_DATABASE: flask_test 
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: