"""Updated AdvModel

Revision ID: 75bbc8dc42e6
Revises: b8ddec9f218d
Create Date: 2024-09-26 13:18:24.500346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bbc8dc42e6'
down_revision = 'b8ddec9f218d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_adv_model_description', table_name='adv_model')
    op.create_index(op.f('ix_adv_model_description'), 'adv_model', ['description'], unique=False)
    op.drop_index('ix_adv_model_owner', table_name='adv_model')
    op.create_index(op.f('ix_adv_model_owner'), 'adv_model', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adv_model_owner'), table_name='adv_model')
    op.create_index('ix_adv_model_owner', 'adv_model', ['owner'], unique=False)
    op.drop_index(op.f('ix_adv_model_description'), table_name='adv_model')
    op.create_index('ix_adv_model_description', 'adv_model', ['description'], unique=False)
    # ### end Alembic commands ###
